dist: xenial
language: java

jdk:
- openjdk11
- openjdk17

addons:
  apt:
    packages:
    - libxml2-utils
  chrome: stable

before_install:
- source ./src/ci/before_install.sh

# skip the Travis-CI install phase because Maven handles that directly
install:
- 'true'

script:
- "./src/ci/build.sh"
